# Generated by Django 5.0.6 on 2024-06-24 09:27

import cv_maker.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('about_me', models.TextField()),
                ('email', models.EmailField(max_length=254, validators=[cv_maker.validators.validate_redberry_email])),
                ('phone_num', models.CharField(max_length=255)),
            ],
        ),
    ]
