# Generated by Django 5.0.6 on 2024-06-24 09:28

import cv_maker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(max_length=255, validators=[cv_maker.validators.validate_georgian_phone_number]),
        ),
    ]
