# Generated by Django 5.0.6 on 2024-06-24 16:04

import cv_maker.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0002_alter_profile_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('S', 'სტუდენტი'), ('B', 'ბაკალავრი'), ('M', 'დოქტორანტი')], max_length=255)),
                ('finish_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('employer', models.CharField(max_length=255)),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), cv_maker.validators.validate_georgian]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), cv_maker.validators.validate_georgian]),
        ),
    ]
