# Generated by Django 5.0.6 on 2024-06-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0003_education_experience_alter_profile_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cv_maker.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='cv_maker.profile'),
            preserve_default=False,
        ),
    ]
